apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vexobj.fullname" . }}-config
  labels:
    {{- include "vexobj.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- .Values.config | nindent 4 }}
